/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Cadastrar;

import DAO.ClienteDAO;
import java.sql.PreparedStatement;
import DAO.Conexao;
import Modelo.Cliente;
import java.sql.*;
import javax.swing.JOptionPane;
import DAO.FuncionarioDAO;
import DAO.Conexao;
import Modelo.Funcionario;
import Principal.Menu;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class CadastrarCliente extends javax.swing.JFrame {

    public CadastrarCliente() {
        initComponents();
         setSize(870,700);
        ProximoId();
         setResizable(false);
        setSize(850,630);
         setLocationRelativeTo(this);
    }
   
     private void ProximoId(){
        Connection con = Conexao.AbrirConexao();
        ClienteDAO sql  = new ClienteDAO(con);
        List<Cliente> lista = new ArrayList<>();
        lista = sql.ProximoCliente();
        for(Cliente a : lista){
        int codigo = a.getCodigo()+1;
        id.setText(""+codigo);
        }
        Conexao.FecharConexao(con);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        Jtf_nome = new javax.swing.JTextField();
        jtf_rg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf_cpf = new javax.swing.JFormattedTextField();
        jtf_telefone = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        Jtf_nascimento = new javax.swing.JFormattedTextField();
        jtf_rua = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        numeror = new javax.swing.JTextField();
        jtf_bairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtf_cep = new javax.swing.JFormattedTextField();
        jtf_email = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 100);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("CEP");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(600, 380, 40, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Nº do Cliente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 130, 130, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Nome:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 170, 80, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("RG:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 220, 50, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Rua");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(40, 330, 70, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Telefone:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 270, 90, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Bairro");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 380, 70, 30);

        id.setEditable(false);
        getContentPane().add(id);
        id.setBounds(130, 130, 190, 30);
        getContentPane().add(Jtf_nome);
        Jtf_nome.setBounds(130, 170, 700, 30);
        getContentPane().add(jtf_rg);
        jtf_rg.setBounds(130, 220, 250, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 430, 60, 30);

        try {
            jtf_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jtf_cpf);
        jtf_cpf.setBounds(460, 220, 370, 30);

        try {
            jtf_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)###-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jtf_telefone);
        jtf_telefone.setBounds(130, 270, 250, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("CPF:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(410, 220, 50, 30);

        try {
            Jtf_nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(Jtf_nascimento);
        Jtf_nascimento.setBounds(620, 270, 210, 30);
        getContentPane().add(jtf_rua);
        jtf_rua.setBounds(130, 330, 450, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("DATA DE NASCIMENTO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(400, 270, 230, 30);
        getContentPane().add(numeror);
        numeror.setBounds(650, 330, 180, 30);
        getContentPane().add(jtf_bairro);
        jtf_bairro.setBounds(130, 380, 440, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Nº");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(610, 330, 40, 30);

        try {
            jtf_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jtf_cep);
        jtf_cep.setBounds(650, 380, 180, 30);
        getContentPane().add(jtf_email);
        jtf_email.setBounds(130, 430, 650, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cadastrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(159, 159, 159)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 490, 840, 100);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 100, 840, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          
            
          String nome  = Jtf_nome.getText();
          String nascimento = Jtf_nascimento.getText();
          String cep = jtf_cep.getText();
          String rua = jtf_rua.getText();
          String numero = numeror.getText();
          String bairro = jtf_bairro.getText(); 
          String email = jtf_email.getText();
          String fone = jtf_telefone.getText();
          String cpf = jtf_cpf.getText();
          String rg = jtf_rg.getText();
          
          if (nome.equals("") ||  nascimento.equals("") || cep.equals("") || rua.equals("") || bairro.equals("") || fone.equals("") || cpf.equals("") || rg.equals("")){
          
              JOptionPane.showMessageDialog(null, "nenhum campo pode estar vazio", "video locadora", JOptionPane.WARNING_MESSAGE);
          
          }else{
              
              Connection con = Conexao.AbrirConexao();
              ClienteDAO sql = new ClienteDAO(con);
              
              int n = Integer.parseInt(numero);
              Cliente a = new Cliente();
              
              a.setNome(nome);
              a.setNascimento(nascimento);
              a.setRG(rg);
              a.setCPF(cpf);
              a.setEmail(email);
              a.setTelefone(fone);
              a.setBairro(bairro);
              a.setRua(rua);
              a.setNumero(n);
              a.setCEP(cep);
              
              sql.Inserir_Cliente(a);
              Conexao.FecharConexao(con);
              
              Jtf_nome.setText("");
              jtf_cep.setText("");
              id.setText("");
              jtf_bairro.setText("");
              jtf_email.setText("");
              jtf_telefone.setText("");
              jtf_rua.setText("");
              Jtf_nascimento.setText("");
              jtf_rg.setText("");
              jtf_cpf.setText("");
              numeror.setText("");
              
              
              JOptionPane.showMessageDialog(null, "cadastro realizado com sucesso", "video locadora", JOptionPane.INFORMATION_MESSAGE);
             
              new Menu().setVisible(true);
 dispose();
              
          }
          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.Jtf_nome.setText("");
 this.Jtf_nascimento.setText("");
 this.jtf_cep.setText("");
 this.jtf_rua.setText("");
 this.numeror.setText("");
 this.jtf_bairro.setText("");
 this.jtf_email.setText("");
 this.jtf_telefone.setText("");
 this.jtf_cpf.setText("");
 this.jtf_rg.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Jtf_nascimento;
    private javax.swing.JTextField Jtf_nome;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jtf_bairro;
    private javax.swing.JFormattedTextField jtf_cep;
    private javax.swing.JFormattedTextField jtf_cpf;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JTextField jtf_rg;
    private javax.swing.JTextField jtf_rua;
    private javax.swing.JFormattedTextField jtf_telefone;
    private javax.swing.JTextField numeror;
    // End of variables declaration//GEN-END:variables
}
