/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Consultar;

import DAO.ClienteDAO;
import DAO.Conexao;
import Modelo.Cliente;
import Principal.Menu;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Valéria
 */
public class ConsultarCliente extends javax.swing.JFrame {

    /**
     * Creates new form ConsultarCliente
     */
    public ConsultarCliente() {
        initComponents();
        AtualizaTable();
        setLocationRelativeTo(this);
        setResizable(true);
        setTitle("Consultar Clientes");
    }
    private void AtualizaTable(){
        Connection con = Conexao.AbrirConexao();
        ClienteDAO bd = new ClienteDAO(con);
        List<Cliente> lista = new ArrayList<>();
        lista = bd.ListarCliente();
        DefaultTableModel tbm = (DefaultTableModel) tabela.getModel();
        while(tbm.getRowCount() > 0){
            tbm.removeRow(0);
        }
        int i = 0;
        for (Cliente tab : lista){
            tbm.addRow(new String[i]);
            tabela.setValueAt(tab.getCodigo(), i, 0);
            tabela.setValueAt(tab.getNome(), i, 1);
            tabela.setValueAt(tab.getRG(), i, 2);
            tabela.setValueAt(tab.getCPF(), i, 3);
            tabela.setValueAt(tab.getTelefone(), i, 4);
            tabela.setValueAt(tab.getEmail(), i, 5);
            i++;


        }
        Conexao.FecharConexao(con);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        pesquisarnome = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jButton7.setText("RG");

        jLabel1.setText("Pesquisa por código:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(150, 30, 210, 30);

        jLabel2.setText("Pesquisa por nome:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 160, 50);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(630, 30, 96, 32);

        pesquisarnome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar.jpg"))); // NOI18N
        pesquisarnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarnomeActionPerformed(evt);
            }
        });
        jPanel1.add(pesquisarnome);
        pesquisarnome.setBounds(370, 30, 40, 29);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/pesquisar.jpg"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(740, 30, 40, 30);

        jButton3.setText("VOLTAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(880, 50, 100, 30);

        jButton4.setText("TODOS");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(880, 10, 100, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 10, 1010, 90);

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cliente", "RG", "CPF", "Telefone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 110, 960, 402);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Connection con = Conexao.AbrirConexao();
    ClienteDAO bd = new ClienteDAO(con);
     List<Cliente> lista = new ArrayList<>();
        String cod = jTextField2.getText();
        lista = bd.Pesquisar_Cod_Cliente(cod);
        DefaultTableModel tbm = (DefaultTableModel) tabela.getModel();
        
    
    while(tbm.getRowCount() > 0){
    tbm.removeRow(0);
    }
    int i = 0;
    for(Cliente tab : lista){
    tbm.addRow(new String[i]);
   tabela.setValueAt(tab.getCodigo(), i,0);
    tabela.setValueAt(tab.getNome(),i,1);
    tabela.setValueAt(tab.getRG(),i,2);
    tabela.setValueAt(tab.getCPF(),i,3);
    tabela.setValueAt(tab.getTelefone(),i,4);
    tabela.setValueAt(tab.getEmail(),i,5);
    // Limpar campos de pesquisa
    jTextField1.setText("");
    jTextField2.setText("");
    i++;
    }
    Conexao.FecharConexao(con);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      new Menu().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void pesquisarnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarnomeActionPerformed
      Connection con = Conexao.AbrirConexao();
    ClienteDAO bd = new ClienteDAO(con);
     List<Cliente> lista = new ArrayList<>();
        String nome = jTextField1.getText();
        lista = bd.Pesquisar_Nome_Cliente(nome);
        DefaultTableModel tbm = (DefaultTableModel) tabela.getModel();
        
    
    while(tbm.getRowCount() > 0){
    tbm.removeRow(0);
    }
    int i = 0;
    for(Cliente tab : lista){
    tbm.addRow(new String[i]);
   tabela.setValueAt(tab.getCodigo(), i,0);
    tabela.setValueAt(tab.getNome(),i,1);
    tabela.setValueAt(tab.getRG(),i,2);
    tabela.setValueAt(tab.getCPF(),i,3);
    tabela.setValueAt(tab.getTelefone(),i,4);
    tabela.setValueAt(tab.getEmail(),i,5);
    i++;
    }
    Conexao.FecharConexao(con);
    
        
    }//GEN-LAST:event_pesquisarnomeActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
   String codigo = jTextField2.getText();
 
    Connection con = Conexao.AbrirConexao();
    ClienteDAO bd = new ClienteDAO(con);
     
        List<Cliente> lista = new ArrayList<>();
        lista = bd.Pesquisar_Cod_Cliente(codigo);
        DefaultTableModel tbm = (DefaultTableModel) tabela.getModel();
        
    
    while(tbm.getRowCount() > 0){
    tbm.removeRow(0);
    }
    int i = 0;
    for(Cliente tab : lista){
    tbm.addRow(new String[i]);
    tabela.setValueAt(tab.getCodigo(), i,0);
    tabela.setValueAt(tab.getNome(),i,1);
    tabela.setValueAt(tab.getRG(),i,2);
    tabela.setValueAt(tab.getCPF(),i,3);
    tabela.setValueAt(tab.getTelefone(),i,4);
    tabela.setValueAt(tab.getEmail(),i,5);
    
   
    i++;
    }
    Conexao.FecharConexao(con);
    
   
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          AtualizaTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton pesquisarnome;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
