/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Alterar;
import DAO.ClienteDAO;
import DAO.Conexao;
import Modelo.Cliente;
import Principal.Menu;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

public class AlterarCliente extends javax.swing.JFrame {

    public AlterarCliente() {
        initComponents();
        setTitle("Alterar Informações");
         setResizable(false);
        setSize(740,630);
         setLocationRelativeTo(this);
    }


    private void InserirDados(int cod){
    Connection con = Conexao.AbrirConexao();
    ClienteDAO sql  = new ClienteDAO(con);
    List<Cliente> lista = new ArrayList<>();
    lista = sql.CapturarCliente(cod);
    for(Cliente a : lista){
    nr.setText(""+a.getCodigo());
    nome.setText(""+a.getNome());
    jtf_cep.setText(""+a.getCEP());
    nr.setText(""+a.getNumero());
    jtf_bairro.setText(""+a.getBairro());
    jtf_email.setText(""+a.getEmail());
    jtf_telefone.setText(""+a.getTelefone());
    jtf_rua.setText(""+a.getRua());
    jtf_nascimento.setText(""+a.getNascimento());
    rg.setText(""+a.getRG());
    jtf_cpf.setText(""+a.getCPF());
    
    }
    Conexao.FecharConexao(con);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtf_email = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtf_bairro = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtf_rua = new javax.swing.JTextField();
        jtf_telefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        cod1 = new javax.swing.JTextField();
        btaltera = new javax.swing.JButton();
        jtf_cpf = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jtf_nascimento = new javax.swing.JFormattedTextField();
        nr = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_cep = new javax.swing.JFormattedTextField();

        jFormattedTextField1.setText("jFormattedTextField1");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("ALTERAR CLIENTE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(256, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 100);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jButton1.setText("Cancelar");

        alterar.setText("Alterar");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(124, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addComponent(alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(205, 205, 205))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 490, 840, 100);

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel3.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Nº do Cliente");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(20, 60, 130, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("CODIGO:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(20, 20, 130, 30);
        jPanel3.add(jtf_email);
        jtf_email.setBounds(140, 320, 250, 30);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Email");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(30, 330, 60, 30);
        jPanel3.add(jtf_bairro);
        jtf_bairro.setBounds(140, 280, 250, 30);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setText("Bairro");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(30, 290, 70, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Rua");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(30, 240, 70, 40);
        jPanel3.add(jtf_rua);
        jtf_rua.setBounds(140, 240, 250, 30);

        try {
            jtf_telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)###-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(jtf_telefone);
        jtf_telefone.setBounds(140, 200, 250, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Telefone:");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 190, 90, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel5.setText("RG:");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(20, 150, 50, 30);
        jPanel3.add(rg);
        rg.setBounds(140, 150, 250, 30);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("CPF:");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(400, 200, 50, 30);
        jPanel3.add(nome);
        nome.setBounds(140, 100, 380, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel4.setText("Nome:");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(20, 110, 80, 30);

        codigo.setEditable(false);
        jPanel3.add(codigo);
        codigo.setBounds(140, 60, 190, 30);
        jPanel3.add(cod1);
        cod1.setBounds(140, 20, 222, 32);

        btaltera.setText("OK");
        btaltera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btalteraActionPerformed(evt);
            }
        });
        jPanel3.add(btaltera);
        btaltera.setBounds(380, 20, 49, 25);

        try {
            jtf_cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(jtf_cpf);
        jtf_cpf.setBounds(460, 200, 260, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setText("DATA DE NASCIMENTO");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(400, 160, 230, 30);

        try {
            jtf_nascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(jtf_nascimento);
        jtf_nascimento.setBounds(620, 160, 100, 30);
        jPanel3.add(nr);
        nr.setBounds(460, 240, 180, 30);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Nº");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(410, 240, 40, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("CEP");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(410, 280, 40, 30);

        try {
            jtf_cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel3.add(jtf_cep);
        jtf_cep.setBounds(460, 280, 180, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 100, 840, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btalteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btalteraActionPerformed
    String codigo = cod1.getText();
        Connection con = Conexao.AbrirConexao();
        ClienteDAO sql = new ClienteDAO(con);
        int cod  = Integer.parseInt(codigo);
      
        if(sql.Testar_Cliente(cod) == false){
        JOptionPane.showMessageDialog(null,"Codigo não Encontrado no Banco","Vidio Locadora",JOptionPane.WARNING_MESSAGE);
        Conexao.FecharConexao(con);
        }
        
        if(codigo.equals("")){
        JOptionPane.showMessageDialog(null,"Digite um codigo para Atualizar","Video Locadora",JOptionPane.WARNING_MESSAGE);
        }
      this.codigo.setText("");
       nome.setText("");
       jtf_cep.setText("");
       nr.setText("");
       jtf_bairro.setText("");
       jtf_email.setText("");
       jtf_telefone.setText("");
       jtf_rua.setText("");
       jtf_nascimento.setText("");
       rg.setText("");
      jtf_cpf.setText("");
        
        InserirDados(cod);
        
          
    }//GEN-LAST:event_btalteraActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
          String nome1  = nome.getText();
          String nascimento = jtf_nascimento.getText();
          String cep = jtf_cep.getText();
          String rua = jtf_rua.getText();
          String numero = codigo.getText();
          String bairro = jtf_bairro.getText(); 
          String email = jtf_email.getText();
          String fone = jtf_telefone.getText();
          String cpf = jtf_cpf.getText();
          String rg1 = rg.getText();
          String cod = codigo.getText();
          if(nome.equals("")){
              JOptionPane.showMessageDialog(null, "nenhum campo pode estar vazio", "video locadora", JOptionPane.WARNING_MESSAGE);
              
          }
          else{
              Connection con = Conexao.AbrirConexao();
              ClienteDAO sql = new ClienteDAO(con);
              int n = Integer.parseInt(numero);
              Cliente a = new Cliente();
              
              a.setNome(nome1);
              a.setNascimento(nascimento);
              a.setCEP(cep);
              a.setRua(rua);
              a.setNumero(n);
              a.setBairro(bairro);
              a.setEmail(email);
              a.setTelefone(fone);
              a.setCPF(cpf);
              a.setRG(rg1);
           
             
              Conexao.FecharConexao(con);
              nome.setText("");
              jtf_cep.setText("");
              codigo.setText("");
              jtf_bairro.setText("");
              jtf_email.setText("");
              jtf_telefone.setText("");
              jtf_rua.setText("");
              jtf_nascimento.setText("");
              rg.setText("");
              jtf_cpf.setText("");
              JOptionPane.showMessageDialog(null, "cadastro realizado com sucesso", "video locadora", JOptionPane.INFORMATION_MESSAGE);
              dispose();
                 }
    }//GEN-LAST:event_alterarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         this.nome.setText("");
        this.jtf_nascimento.setText("");
        this.jtf_cep.setText("");
        this.jtf_rua.setText("");
        this.nr.setText("");
        this.jtf_bairro.setText("");
        this.jtf_email.setText("");
        this.jtf_telefone.setText("");
        this.jtf_cpf.setText("");
        this.rg.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton btaltera;
    private javax.swing.JTextField cod1;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jtf_bairro;
    private javax.swing.JFormattedTextField jtf_cep;
    private javax.swing.JFormattedTextField jtf_cpf;
    private javax.swing.JTextField jtf_email;
    private javax.swing.JFormattedTextField jtf_nascimento;
    private javax.swing.JTextField jtf_rua;
    private javax.swing.JFormattedTextField jtf_telefone;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField nr;
    private javax.swing.JTextField rg;
    // End of variables declaration//GEN-END:variables
}
